name: floor_cv
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  collection: ^1.18.0
  dio: ^5.7.0
  drift: ^2.20.2
  drift_flutter: ^0.2.0
  file_icon: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  mime: ^1.0.6
  open_file: ^3.5.6
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  timeago: ^3.7.0
  timeago_flutter: ^3.7.0
  uuid: ^4.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  drift_dev: ^2.20.3
flutter:
  uses-material-design: true
  fonts:
    - family: Atkinson Hyperlegible
      fonts:
        - asset: assets/fonts/AtkinsonHyperlegible-Bold.ttf
        - asset: assets/fonts/AtkinsonHyperlegible-BoldItalic.ttf
        - asset: assets/fonts/AtkinsonHyperlegible-Italic.ttf
        - asset: assets/fonts/AtkinsonHyperlegible-Regular.ttf