# flutter build web --no-tree-shake-icons --release
# firebase deploy
name: paper_cv
description: "paper_cv"
publish_to: 'none'
version: 1.3.1+10
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  camera: ^0.11.0+2
  collection: ^1.18.0
  desktop_drop: ^0.5.0
  dio: ^5.7.0
  dotted_border: ^2.1.0
  drift: ^2.20.2
  drift_flutter: ^0.2.0
  file_icon: ^1.0.0
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_logs: ^2.2.1
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^2.4.4
  gal: ^2.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  mime: ^1.0.6
  native_device_orientation: ^2.0.3
  open_file: ^3.5.6
  package_info_plus: ^8.1.2
  palette_generator: ^0.3.3+5
  path_provider: ^2.1.4
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.5
  table_calendar: ^3.1.3
  timeago: ^3.7.0
  timeago_flutter: ^3.7.0
  url_launcher: ^6.3.1
  uuid: ^4.5.0
  wakelock_plus: ^1.2.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  drift_dev: ^2.20.3
  intl_utils: ^2.8.8 # dart run intl_utils:generate

flutter:
  assets:
    - assets/
  uses-material-design: true
  fonts:
    - family: Atkinson Hyperlegible
      fonts:
        - asset: assets/fonts/AtkinsonHyperlegible-Bold.ttf
        - asset: assets/fonts/AtkinsonHyperlegible-BoldItalic.ttf
        - asset: assets/fonts/AtkinsonHyperlegible-Italic.ttf
        - asset: assets/fonts/AtkinsonHyperlegible-Regular.ttf