name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLOOR_CV }}
          channelId: live
          projectId: floor-cv
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
